# Generated by Django 5.2.15 on 2026-06-26 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Brand Name")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=220, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, verbose_name="Country of Origin"),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="Website URL")),
                (
                    "support_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Support Email"),
                ),
                (
                    "support_phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Support Phone"),
                ),
                (
                    "warranty_policy_text",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable warranty terms for this brand.",
                        verbose_name="Warranty Policy",
                    ),
                ),
                (
                    "warranty_months_default",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Applied to all products unless overridden at product level.",
                        verbose_name="Default Warranty (months)",
                    ),
                ),
                (
                    "is_warranty_transferable",
                    models.BooleanField(
                        default=False,
                        help_text="Can warranty be transferred if the device is resold?",
                        verbose_name="Warranty Transferable",
                    ),
                ),
                (
                    "service_policy_text",
                    models.TextField(
                        blank=True,
                        help_text="Repair and service terms for this brand.",
                        verbose_name="Service Policy",
                    ),
                ),
                (
                    "service_turnaround_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Typical repair / service SLA in business days.",
                        null=True,
                        verbose_name="Service Turnaround (days)",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List: [{"name": "", "number": "", "issued_by": "", "valid_until": "YYYY-MM-DD"}]',
                        verbose_name="Certifications",
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        help_text="Central brand documentation / IFU portal.",
                        verbose_name="Documentation Portal URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BrandDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("catalogue", "Product Catalogue"),
                            ("certification", "Certification"),
                            ("ifu", "Instructions for Use (IFU)"),
                            ("price_list", "Price List"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="brands/documents/", verbose_name="File"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Use if the document is hosted externally.",
                        verbose_name="External URL",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If true, visible to authenticated customers.",
                        verbose_name="Public",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="brands.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Document",
                "verbose_name_plural": "Brand Documents",
                "ordering": ["brand", "document_type", "title"],
            },
        ),
    ]
