# Generated by Django 5.2.15 on 2026-07-01 09:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productpricing",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product Pricing",
                "verbose_name_plural": "Product Pricing",
            },
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="dealer_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Special wholesale price for verified dealers only. Must be ≤ Selling Price.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Dealer Price",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                help_text="Applicable GST slab (e.g. 0, 5, 12, 18, 28).",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="GST Percentage (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="mrp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Original / maximum retail price before any discount.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="MRP (Maximum Retail Price)",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="offer_end_date",
            field=models.DateField(
                blank=True,
                help_text="Offer expires after this date (inclusive).",
                null=True,
                verbose_name="Offer End Date",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="offer_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Temporary discounted price. Must be ≤ Selling Price.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Offer Price",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="offer_start_date",
            field=models.DateField(
                blank=True,
                help_text="Offer activates from this date (inclusive).",
                null=True,
                verbose_name="Offer Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Standard selling price. Must be ≤ MRP.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Selling Price",
            ),
        ),
    ]
