# Generated by Django 5.2.15 on 2026-07-17 05:42

import apps.warranty.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_cancellation_reason_order_cancelled_at_and_more"),
        ("products", "0002_product_warranty_contact_details_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "claim_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Claim Number",
                    ),
                ),
                ("description", models.TextField(verbose_name="Problem Description")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=30,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("need_more_info", "Need More Info"),
                            ("approved", "Approved"),
                            ("assigned", "Assigned"),
                            ("repair_in_progress", "Repair In Progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "assigned_provider",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Assigned Provider"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, default="", verbose_name="Admin Notes"),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, default="", verbose_name="Resolution Details"),
                ),
            ],
            options={
                "verbose_name": "Warranty Claim",
                "verbose_name_plural": "Warranty Claims",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarrantyAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "file",
                    models.FileField(
                        upload_to="warranty_attachments/%Y/%m/",
                        validators=[apps.warranty.models.validate_attachment_file],
                        verbose_name="Attachment File",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("product_image", "Product Image"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="warranty.warrantyclaim",
                        verbose_name="Warranty Claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warranty Attachment",
                "verbose_name_plural": "Warranty Attachments",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("action", models.CharField(max_length=200, verbose_name="Action")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="warranty.warrantyclaim",
                        verbose_name="Warranty Claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Timeline Event",
                "verbose_name_plural": "Claim Timeline Events",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarrantyRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Serial Number"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Purchase Date")),
                ("warranty_start", models.DateField(verbose_name="Warranty Start Date")),
                ("warranty_end", models.DateField(verbose_name="Warranty End Date")),
                (
                    "warranty_provider",
                    models.CharField(
                        choices=[
                            ("faazo", "FAAZO"),
                            ("manufacturer", "Manufacturer"),
                            ("distributor", "Distributor"),
                            ("third_party", "Third Party"),
                        ],
                        default="manufacturer",
                        max_length=50,
                        verbose_name="Warranty Provider",
                    ),
                ),
                (
                    "warranty_status",
                    models.CharField(
                        choices=[("registered", "Registered"), ("expired", "Expired")],
                        default="registered",
                        max_length=50,
                        verbose_name="Warranty Status",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warranty_registrations",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warranty_registrations",
                        to="orders.orderitem",
                        verbose_name="Order Item",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warranty_registrations",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warranty_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warranty Registration",
                "verbose_name_plural": "Warranty Registrations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="warranty.warrantyregistration",
                verbose_name="Warranty Registration",
            ),
        ),
    ]
