# Generated by Django 5.2.15 on 2026-07-17 06:39

import apps.warranty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warranty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrantyregistration",
            name="admin_notes",
            field=models.TextField(blank=True, default="", verbose_name="Admin Notes"),
        ),
        migrations.AddField(
            model_name="warrantyregistration",
            name="invoice",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="warranty_invoices/%Y/%m/",
                validators=[apps.warranty.models.validate_attachment_file],
                verbose_name="Purchase Invoice",
            ),
        ),
        migrations.AddField(
            model_name="warrantyregistration",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="warrantyregistration",
            name="warranty_provider",
            field=models.CharField(
                choices=[
                    ("faazo", "FAAZO"),
                    ("manufacturer", "Manufacturer"),
                    ("distributor", "Distributor"),
                    ("third_party", "Third Party"),
                ],
                default="faazo",
                max_length=50,
                verbose_name="Warranty Provider",
            ),
        ),
        migrations.AlterField(
            model_name="warrantyregistration",
            name="warranty_status",
            field=models.CharField(
                choices=[
                    ("pending_registration", "Pending Registration"),
                    ("pending_verification", "Pending Verification"),
                    ("need_more_info", "Need More Info"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending_registration",
                max_length=50,
                verbose_name="Warranty Status",
            ),
        ),
    ]
