# Generated by Django 5.2.15 on 2026-06-22 10:51

import apps.users.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="Full Name")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer / Dentist"),
                            ("dealer", "Dealer"),
                            ("admin", "Administrator"),
                        ],
                        db_index=True,
                        default="customer",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="E.164 format recommended (e.g. +919876543210). Unique per user. OTP verification will be added in v2.0.",
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True when mobile OTP is successfully verified. OTP logic is NOT implemented in v1.0 — field reserved for v2.0.",
                        verbose_name="Phone Verified",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Email Verified"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to deactivate account without deleting.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Grants Django Admin access.",
                        verbose_name="Staff Status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="Primary Clinic",
                        help_text="e.g. Primary Clinic, Branch, Home",
                        max_length=50,
                        verbose_name="Address Label",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="Contact Full Name")),
                ("mobile", models.CharField(max_length=15, verbose_name="Contact Mobile")),
                ("line1", models.CharField(max_length=255, verbose_name="Address Line 1")),
                (
                    "line2",
                    models.CharField(blank=True, max_length=255, verbose_name="Address Line 2"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                ("pincode", models.CharField(max_length=6, verbose_name="Pincode")),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping"),
                            ("billing", "Billing"),
                            ("both", "Shipping & Billing"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="Address Type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Default Address"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="Avatar"
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Clinic / Organisation Name"
                    ),
                ),
                (
                    "dental_license",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Used for clinic info and warranty.",
                        max_length=100,
                        verbose_name="Dental License Number",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio / Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email", "is_active"], name="users_email_a7cfd1_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role", "is_active"], name="users_role_a8f2ba_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["user", "is_default"], name="addresses_user_id_41b398_idx"),
        ),
    ]
