# Generated by Django 5.2.15 on 2026-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="clinic_address",
            field=models.TextField(blank=True, verbose_name="Clinic Address"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="clinic_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Clinic Email"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="clinic_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Clinic Phone Number"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="clinic_registration_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Clinic Registration Number"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dental_specialty",
            field=models.CharField(
                blank=True,
                help_text="e.g. Endodontics, Orthodontics, Prosthodontics",
                max_length=100,
                verbose_name="Dental Specialty",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                help_text="e.g. Male, Female, Non-binary, Prefer not to say",
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gst_number",
            field=models.CharField(
                blank=True,
                help_text="15-character GST Identification Number",
                max_length=15,
                verbose_name="GST Number",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profession",
            field=models.CharField(
                blank=True,
                help_text="e.g. Dentist, Periodontist, Oral Surgeon",
                max_length=100,
                verbose_name="Profession",
            ),
        ),
    ]
