# Generated by Django 5.2.15 on 2026-07-09 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userprofile_noncommerce_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Admin Notes"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_blocked",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Blocked"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is Deleted"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="Tags"),
        ),
        migrations.CreateModel(
            name="CustomerAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "action_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_admin_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Action By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Audit Log",
                "verbose_name_plural": "Customer Audit Logs",
                "db_table": "customer_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
