# Generated by Django 5.2.15 on 2026-06-22 11:02

import apps.authentication.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of the raw token. Raw token is only in the email.",
                        max_length=64,
                        unique=True,
                        verbose_name="Token Hash (SHA-256)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.authentication.models._email_token_expiry,
                        verbose_name="Expires At",
                    ),
                ),
                ("is_used", models.BooleanField(db_index=True, default=False, verbose_name="Used")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification Token",
                "verbose_name_plural": "Email Verification Tokens",
                "db_table": "email_verification_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_used"], name="email_verif_user_id_35194a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Token Hash (SHA-256)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.authentication.models._reset_token_expiry,
                        verbose_name="Expires At",
                    ),
                ),
                ("is_used", models.BooleanField(db_index=True, default=False, verbose_name="Used")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="Used At")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "db_table": "password_reset_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_used"], name="password_re_user_id_cd37a3_idx")
                ],
            },
        ),
    ]
