# Generated by Django 5.2.15 on 2026-07-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = []
