# Generated by Django 5.2.15 on 2026-07-01 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_seed_pricing_inventory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productinventory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product Inventory",
                "verbose_name_plural": "Product Inventory",
            },
        ),
        migrations.RemoveField(
            model_name="productinventory",
            name="stock_status",
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="allow_backorders",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, customers can purchase this product even when out of stock. The product will be fulfilled when restocked.",
                verbose_name="Allow Backorders",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="current_stock",
            field=models.IntegerField(
                default=0,
                help_text="Total physical units on hand. Cannot be negative.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Current Stock",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="low_stock_threshold",
            field=models.IntegerField(
                default=5,
                help_text="Alert / badge triggers when available_stock falls to or below this value.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Low Stock Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="reserved_stock",
            field=models.IntegerField(
                default=0,
                help_text="Units allocated to pending orders. Managed internally by the Orders module — do not edit manually.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Reserved Stock",
            ),
        ),
    ]
