# Generated by Django 5.2.15 on 2026-06-26 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Product Name")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=320, unique=True, verbose_name="Slug"),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Unique stock-keeping unit code.",
                        max_length=100,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Shown in listing cards. Max 500 chars.",
                        max_length=500,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        help_text="Rich text / HTML. Shown on product detail page.",
                        verbose_name="Full Description",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='String list: ["implant", "surgical", "titanium"]',
                        verbose_name="Tags",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("discontinued", "Discontinued"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Pinned in homepage featured section.",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "launched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this product became / will become publicly visible.",
                        null=True,
                        verbose_name="Launch Date",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "dimensions_cm",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"length": 0, "width": 0, "height": 0}',
                        verbose_name="Dimensions (cm)",
                    ),
                ),
                (
                    "warranty_months_override",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Override the brand default warranty for this product. Leave blank to use Brand.warranty_months_default.",
                        null=True,
                        verbose_name="Warranty Override (months)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="After-sales routing (warranty, service) is resolved through Brand.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="brands.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="categories.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Attribute Name")),
                ("value", models.CharField(max_length=300, verbose_name="Value")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. V, Hz, kg, cm",
                        max_length=30,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute",
                "verbose_name_plural": "Product Attributes",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("brochure", "Brochure"),
                            ("ifu", "Instructions for Use (IFU)"),
                            ("compliance", "Compliance / CE Certificate"),
                            ("manual", "User Manual"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="products/documents/", verbose_name="File"
                    ),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="External URL")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If true, visible to authenticated customers.",
                        verbose_name="Public",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Document",
                "verbose_name_plural": "Product Documents",
                "ordering": ["product", "document_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="products/images/", verbose_name="Image")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessibility description for this image.",
                        max_length=200,
                        verbose_name="Alt Text",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Shown as the hero/thumbnail image.",
                        verbose_name="Primary Image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_deleted"], name="products_pr_status_5964c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand", "status"], name="products_pr_brand_i_6bc83e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="products_pr_categor_75eeb5_idx"
            ),
        ),
    ]
