# Generated by Django 5.2.15 on 2026-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="warranty_contact_details",
            field=models.TextField(blank=True, default="", verbose_name="Warranty Contact Details"),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_months",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Warranty period in months. If blank, falls back to brand default.",
                null=True,
                verbose_name="Warranty Months",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_provider",
            field=models.CharField(
                choices=[
                    ("faazo", "FAAZO"),
                    ("manufacturer", "Manufacturer"),
                    ("distributor", "Distributor"),
                    ("third_party", "Third Party"),
                ],
                default="manufacturer",
                max_length=50,
                verbose_name="Warranty Provider",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_terms",
            field=models.TextField(blank=True, default="", verbose_name="Warranty Terms"),
        ),
    ]
