# Generated by Django 5.2.15 on 2026-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_warranty_contact_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="serial_number_required",
            field=models.BooleanField(
                default=False,
                help_text="Toggle if serial number is mandatory for manual registration approval.",
                verbose_name="Serial Number Required",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_website_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Website URL where customer can register warranty for imported brands.",
                verbose_name="Manufacturer Warranty Website",
            ),
        ),
    ]
