# Generated by Django 5.2.15 on 2026-07-06 06:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboDeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Combo Title")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=320, unique=True, verbose_name="Slug"),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, max_length=500, verbose_name="Short Description"),
                ),
                ("full_description", models.TextField(blank=True, verbose_name="Full Description")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="combos/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="combos/banners/", verbose_name="Banner"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Original Price (Calculated)",
                    ),
                ),
                (
                    "combo_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Combo Price",
                    ),
                ),
                (
                    "dealer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Dealer Price",
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Offer Price",
                    ),
                ),
                (
                    "offer_start_date",
                    models.DateField(blank=True, null=True, verbose_name="Offer Start Date"),
                ),
                (
                    "offer_end_date",
                    models.DateField(blank=True, null=True, verbose_name="Offer End Date"),
                ),
                (
                    "is_featured",
                    models.BooleanField(db_index=True, default=False, verbose_name="Featured"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Current Stock",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=150, verbose_name="Meta Title"),
                ),
                ("meta_description", models.TextField(blank=True, verbose_name="Meta Description")),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=255, verbose_name="Meta Keywords"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo Deal",
                "verbose_name_plural": "Combo Deals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComboDealImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="combos/gallery/", verbose_name="Image")),
                ("alt_text", models.CharField(blank=True, max_length=200, verbose_name="Alt Text")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "combo_deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="combos.combodeal",
                        verbose_name="Combo Deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo Image",
                "verbose_name_plural": "Combo Images",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ComboDealProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Quantity")),
                (
                    "combo_deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_products",
                        to="combos.combodeal",
                        verbose_name="Combo Deal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combo_memberships",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo Product",
                "verbose_name_plural": "Combo Products",
            },
        ),
        migrations.AddIndex(
            model_name="combodeal",
            index=models.Index(
                fields=["status", "is_deleted"], name="combos_comb_status_9c1730_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="combodealproduct",
            unique_together={("combo_deal", "product")},
        ),
    ]
