# Generated by Django 5.2.15 on 2026-07-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboDealBannerSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        default="SUPER SAVER BUNDLES", max_length=100, verbose_name="Badge Text"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Premium Combo Deals", max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Equip your clinical workflows with carefully curated packages of leading tools. Save big vs buying individual components.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="combos/banner/",
                        verbose_name="Banner Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo Deal Banner Setting",
                "verbose_name_plural": "Combo Deal Banner Settings",
            },
        ),
    ]
