# Generated by Django 5.2.15 on 2026-07-14 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "event_id",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="Razorpay Event ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g. payment.captured, payment.failed, refund.created",
                        max_length=100,
                        verbose_name="Event Type",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Event Payload")),
                ("processed", models.BooleanField(default=False, verbose_name="Processed")),
                (
                    "processing_error",
                    models.TextField(blank=True, default="", verbose_name="Processing Error"),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "razorpay_order_id",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="Razorpay Order ID"
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Razorpay Payment ID"
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Razorpay Signature"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount (INR)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="INR", max_length=3, verbose_name="Currency"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Payment Method"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Idempotency Key"
                    ),
                ),
                (
                    "checkout_data",
                    models.JSONField(
                        default=dict,
                        help_text="Address ID, delivery method, items, pricing — frozen at order creation time.",
                        verbose_name="Checkout Data Snapshot",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(blank=True, default=dict, verbose_name="Gateway Response"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Error Code"
                    ),
                ),
                (
                    "error_description",
                    models.TextField(blank=True, default="", verbose_name="Error Description"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Verified At"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
