# Generated by Django 5.2.15 on 2026-07-15 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Cancellation Reason"),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Cancelled At"),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cancelled By",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Delivered At"),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="Estimated Delivery Date"),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Invoice Number"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Admin Notes"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Order Number"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="packed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Packed At"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Shipped At"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Shipping Carrier"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tracking Number"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("processing", "Processing"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("processing", "Processing"),
                            ("packed", "Packed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Status History",
                "verbose_name_plural": "Order Status Histories",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
