# Generated by Django 5.2.15 on 2026-07-20 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_cancellation_reason_order_cancelled_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "courier_name",
                    models.CharField(
                        default="Delhivery", max_length=100, verbose_name="Courier Name"
                    ),
                ),
                (
                    "delhivery_shipment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=200,
                        verbose_name="Delhivery Shipment ID",
                    ),
                ),
                (
                    "awb_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="AWB Number",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Tracking Number"
                    ),
                ),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("created", "Shipment Created"),
                            ("pickup_scheduled", "Pickup Scheduled"),
                            ("picked_up", "Picked Up"),
                            ("reached_hub", "Reached Hub"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("failed_delivery", "Failed Delivery"),
                            ("rto_initiated", "RTO Initiated"),
                            ("rto_in_transit", "RTO In Transit"),
                            ("rto_delivered", "RTO Delivered"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=30,
                        verbose_name="Shipment Status",
                    ),
                ),
                (
                    "pickup_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("picked_up", "Picked Up"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Pickup Status",
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Current Location"
                    ),
                ),
                (
                    "pickup_scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="Pickup Scheduled Date"),
                ),
                (
                    "pickup_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Picked Up At"),
                ),
                (
                    "estimated_delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="Estimated Delivery Date"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Delivered At"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last Synced At"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Raw Delhivery API Response"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShipmentTrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "event_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Delhivery Event Code"
                    ),
                ),
                ("event_label", models.CharField(max_length=200, verbose_name="Event Label")),
                (
                    "status_mapped",
                    models.CharField(
                        choices=[
                            ("created", "Shipment Created"),
                            ("pickup_scheduled", "Pickup Scheduled"),
                            ("picked_up", "Picked Up"),
                            ("reached_hub", "Reached Hub"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("failed_delivery", "Failed Delivery"),
                            ("rto_initiated", "RTO Initiated"),
                            ("rto_in_transit", "RTO In Transit"),
                            ("rto_delivered", "RTO Delivered"),
                            ("cancelled", "Cancelled"),
                            ("lost", "Lost"),
                        ],
                        max_length=30,
                        verbose_name="Mapped Shipment Status",
                    ),
                ),
                ("event_timestamp", models.DateTimeField(verbose_name="Event Timestamp")),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Location"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "event_source",
                    models.CharField(
                        choices=[
                            ("api_poll", "API Poll"),
                            ("webhook", "Delhivery Webhook"),
                            ("manual", "Manual Admin"),
                        ],
                        default="api_poll",
                        max_length=50,
                        verbose_name="Event Source",
                    ),
                ),
                (
                    "is_delivered",
                    models.BooleanField(default=False, verbose_name="Is Delivered Event"),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="shipping.shipment",
                        verbose_name="Shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Tracking Event",
                "verbose_name_plural": "Shipment Tracking Events",
                "ordering": ["-event_timestamp"],
                "abstract": False,
            },
        ),
    ]
