# Generated by Django 5.2.15 on 2026-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="api_status_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="API Status Code"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="Error Message"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="execution_time_ms",
            field=models.IntegerField(blank=True, null=True, verbose_name="Execution Time (ms)"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="external_shipment_id",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="External Shipment ID"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pickup_request_id",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Pickup Request ID"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("offline", "Offline Simulation"),
                    ("sandbox", "Delhivery Sandbox"),
                    ("live", "Delhivery Live"),
                ],
                db_index=True,
                default="offline",
                max_length=20,
                verbose_name="Shipping Provider",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="request_payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="Request Payload"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="request_timestamp",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Request Timestamp"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="response_payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="Response Payload"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="response_timestamp",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Response Timestamp"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="tracking_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Tracking URL"
            ),
        ),
    ]
