# Generated by Django 5.2.15 on 2026-06-22 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Company / Clinic Name"),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="GST certificate, trade license, or any business registration document. Served via signed URL in production — never publicly accessible.",
                        upload_to="dealer_documents/%Y/%m/",
                        verbose_name="Registration Document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Application Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Populated by admin when rejecting an application.",
                        max_length=500,
                        verbose_name="Rejection Reason",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Reviewed At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Submitted At"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_dealer_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealer_application",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer Application",
                "verbose_name_plural": "Dealer Applications",
                "db_table": "dealer_applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="dealer_appl_status_a7bd40_idx"
                    )
                ],
            },
        ),
    ]
