# Generated by Django 5.2.15 on 2026-07-13 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0002_dealerapplication_admin_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerapplication",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="GST certificate, trade license, or any business registration document. Served via signed URL in production — never publicly accessible.",
                null=True,
                upload_to="dealer_documents/%Y/%m/",
                verbose_name="Registration Document",
            ),
        ),
        migrations.CreateModel(
            name="DealerApplicationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="dealer_documents/%Y/%m/", verbose_name="Document File"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dealer.dealerapplication",
                        verbose_name="Dealer Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer Application Document",
                "verbose_name_plural": "Dealer Application Documents",
                "db_table": "dealer_application_documents",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
