# Generated by Django 5.2.15 on 2026-06-29 07:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("categories", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(max_length=200, verbose_name="Collection Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Collection Description"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(db_index=True, default=True, verbose_name="Visible"),
                ),
            ],
            options={
                "verbose_name": "Featured Collection",
                "verbose_name_plural": "Featured Collections",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "desktop_image",
                    models.ImageField(
                        blank=True,
                        help_text="Recommended: 1440×480 px or 3:1 aspect ratio.",
                        null=True,
                        upload_to="homepage/hero/desktop/",
                        verbose_name="Desktop Image",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Recommended: 375×500 px or 3:4 aspect ratio.",
                        null=True,
                        upload_to="homepage/hero/mobile/",
                        verbose_name="Mobile Image",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=200, verbose_name="Heading")),
                (
                    "subheading",
                    models.CharField(blank=True, max_length=300, verbose_name="Sub Heading"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        default="Explore Products",
                        max_length=80,
                        verbose_name="CTA Button Text",
                    ),
                ),
                (
                    "cta_link",
                    models.CharField(
                        blank=True,
                        default="#products",
                        help_text="Relative path or anchor e.g. /products or #products",
                        max_length=300,
                        verbose_name="CTA Link",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Hero Slide",
                "verbose_name_plural": "Hero Slides",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LimitedTimeOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="homepage/offers/",
                        verbose_name="Banner Image",
                    ),
                ),
                ("heading", models.CharField(max_length=200, verbose_name="Heading")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "offer_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'UP TO 50% OFF'",
                        max_length=100,
                        verbose_name="Offer Text",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Start Date"),
                ),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="End Date")),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, default="Shop Now", max_length=80, verbose_name="CTA Text"
                    ),
                ),
                ("cta_link", models.CharField(blank=True, max_length=300, verbose_name="CTA Link")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Limited Time Offer",
                "verbose_name_plural": "Limited Time Offers",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("customer_name", models.CharField(max_length=150, verbose_name="Customer Name")),
                (
                    "clinic_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Clinic Name"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="homepage/testimonials/",
                        verbose_name="Customer Photo",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for the photo. Used if no uploaded photo.",
                        verbose_name="Photo URL",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating (1-5)",
                    ),
                ),
                ("review", models.TextField(verbose_name="Review Text")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BestSeller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "display_image",
                    models.ImageField(
                        blank=True,
                        help_text="Override product image for the homepage card.",
                        null=True,
                        upload_to="homepage/bestsellers/",
                        verbose_name="Display Image",
                    ),
                ),
                (
                    "custom_heading",
                    models.CharField(
                        blank=True,
                        help_text="Override product name on the card.",
                        max_length=200,
                        verbose_name="Custom Heading",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Override product short_description on the card.",
                        max_length=300,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(db_index=True, default=True, verbose_name="Visible"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_seller_entries",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Best Seller",
                "verbose_name_plural": "Best Sellers",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExploreSolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="homepage/solutions/",
                        verbose_name="Card Image",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="Override category name for the card heading.",
                        max_length=150,
                        verbose_name="Heading",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(db_index=True, default=True, verbose_name="Visible"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explore_solution_entries",
                        to="categories.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explore Solution",
                "verbose_name_plural": "Explore Solutions",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomepageBrand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "logo_override",
                    models.ImageField(
                        blank=True,
                        help_text="Override the brand logo for homepage display. Falls back to Brand.logo.",
                        null=True,
                        upload_to="homepage/brands/",
                        verbose_name="Logo Override",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(db_index=True, default=True, verbose_name="Visible"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_showcases",
                        to="brands.brand",
                        verbose_name="Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Brand",
                "verbose_name_plural": "Homepage Brands",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomepageCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "card_image",
                    models.ImageField(
                        blank=True,
                        help_text="Override image shown on the homepage card. Falls back to category image.",
                        null=True,
                        upload_to="homepage/categories/",
                        verbose_name="Card Image",
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True,
                        help_text="Override the category name shown on the card.",
                        max_length=100,
                        verbose_name="Title Override",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Key for the predefined SVG icon to show on the card badge. Options: handpiece, imaging, instruments, equipment, materials, chairs, sterilization, endo, implants, other",
                        max_length=50,
                        verbose_name="Icon Key",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(db_index=True, default=True, verbose_name="Visible"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_showcases",
                        to="categories.category",
                        verbose_name="Catalogue Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Category",
                "verbose_name_plural": "Homepage Categories",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(db_index=True, default=True, verbose_name="Visible"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_entries",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommended Product",
                "verbose_name_plural": "Recommended Products",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="homepage.featuredcollection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_collection_items",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Collection Item",
                "verbose_name_plural": "Featured Collection Items",
                "ordering": ["sort_order"],
                "unique_together": {("collection", "product")},
            },
        ),
    ]
